[2022-02-02 04:37:31,727] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-02-02 04:37:31,780] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-02-02 04:37:31,782] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 04:37:31,784] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 04:37:31,785] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 04:37:31,836] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_job> on 2019-01-02 06:00:00+00:00
[2022-02-02 04:37:31,846] {standard_task_runner.py:52} INFO - Started process 3484 to run task
[2022-02-02 04:37:31,857] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'download_ingest_2_gcs_dag', 'local_to_gcs_job', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/load_gsc_assgnment.py', '--cfg-path', '/tmp/tmpzuj9ingn', '--error-file', '/tmp/tmp_a42s7ay']
[2022-02-02 04:37:31,860] {standard_task_runner.py:77} INFO - Job 255: Subtask local_to_gcs_job
[2022-02-02 04:37:32,031] {logging_mixin.py:109} INFO - Running <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [running]> on host 3082aca3aebc
[2022-02-02 04:37:32,195] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 04:37:32,273] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_ingest_2_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-02-02 04:37:32,407] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_gsc_assgnment.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-01.parquet'
[2022-02-02 04:37:32,473] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=download_ingest_2_gcs_dag, task_id=local_to_gcs_job, execution_date=20190102T060000, start_date=20220202T043731, end_date=20220202T043732
[2022-02-02 04:37:32,545] {standard_task_runner.py:92} ERROR - Failed to execute job 255 for task local_to_gcs_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_gsc_assgnment.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-01.parquet'
[2022-02-02 04:37:32,593] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-02 04:37:32,767] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-02 04:50:24,194] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-02-02 04:50:24,258] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-02-02 04:50:24,260] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 04:50:24,261] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 04:50:24,263] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 04:50:24,329] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_job> on 2019-01-02 06:00:00+00:00
[2022-02-02 04:50:24,342] {standard_task_runner.py:52} INFO - Started process 4185 to run task
[2022-02-02 04:50:24,363] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'download_ingest_2_gcs_dag', 'local_to_gcs_job', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/load_gsc_assgnment.py', '--cfg-path', '/tmp/tmp46yns13m', '--error-file', '/tmp/tmpfnwru1a2']
[2022-02-02 04:50:24,367] {standard_task_runner.py:77} INFO - Job 259: Subtask local_to_gcs_job
[2022-02-02 04:50:24,584] {logging_mixin.py:109} INFO - Running <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [running]> on host 3082aca3aebc
[2022-02-02 04:50:24,743] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 04:50:24,812] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_ingest_2_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-02-02 04:50:44,615] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 04:50:44,662] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=download_ingest_2_gcs_dag, task_id=local_to_gcs_job, execution_date=20190102T060000, start_date=20220202T045024, end_date=20220202T045044
[2022-02-02 04:50:44,775] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 04:50:44,880] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-02 06:15:15,966] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-02-02 06:15:16,027] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-02-02 06:15:16,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 06:15:16,031] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 06:15:16,032] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 06:15:16,089] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_job> on 2019-01-02 06:00:00+00:00
[2022-02-02 06:15:16,102] {standard_task_runner.py:52} INFO - Started process 8833 to run task
[2022-02-02 06:15:16,115] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'download_ingest_2_gcs_dag', 'local_to_gcs_job', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/download_ingest_2_gsc_assgnment.py', '--cfg-path', '/tmp/tmpir4l2d7x', '--error-file', '/tmp/tmpq4r6x_z3']
[2022-02-02 06:15:16,118] {standard_task_runner.py:77} INFO - Job 282: Subtask local_to_gcs_job
[2022-02-02 06:15:16,298] {logging_mixin.py:109} INFO - Running <TaskInstance: download_ingest_2_gcs_dag.local_to_gcs_job scheduled__2019-01-02T06:00:00+00:00 [running]> on host 3082aca3aebc
[2022-02-02 06:15:16,451] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 06:15:16,525] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_ingest_2_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-02-02 06:15:48,384] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 06:15:48,517] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=download_ingest_2_gcs_dag, task_id=local_to_gcs_job, execution_date=20190102T060000, start_date=20220202T061515, end_date=20220202T061548
[2022-02-02 06:15:48,727] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 06:15:49,018] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
