[2022-01-31 04:18:01,458] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testing_dag.wget manual__2022-01-31T04:17:59.474204+00:00 [queued]>
[2022-01-31 04:18:01,509] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testing_dag.wget manual__2022-01-31T04:17:59.474204+00:00 [queued]>
[2022-01-31 04:18:01,511] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 04:18:01,513] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-31 04:18:01,514] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 04:18:01,574] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-01-31 04:17:59.474204+00:00
[2022-01-31 04:18:01,582] {standard_task_runner.py:52} INFO - Started process 5019 to run task
[2022-01-31 04:18:01,592] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'wget', 'manual__2022-01-31T04:17:59.474204+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/testing_dag.py', '--cfg-path', '/tmp/tmplwsr87ti', '--error-file', '/tmp/tmp4a5a80ra']
[2022-01-31 04:18:01,595] {standard_task_runner.py:77} INFO - Job 88: Subtask wget
[2022-01-31 04:18:01,796] {logging_mixin.py:109} INFO - Running <TaskInstance: testing_dag.wget manual__2022-01-31T04:17:59.474204+00:00 [running]> on host 5beebf73c64a
[2022-01-31 04:18:02,007] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=testing_dag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T04:17:59.474204+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-31T04:17:59.474204+00:00
[2022-01-31 04:18:02,014] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-31 04:18:02,017] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wgethttps://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv -O /opt/***/output.csv']
[2022-01-31 04:18:02,037] {subprocess.py:85} INFO - Output:
[2022-01-31 04:18:02,101] {subprocess.py:89} INFO - /bin/bash: wgethttps://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv: No such file or directory
[2022-01-31 04:18:02,106] {subprocess.py:93} INFO - Command exited with return code 127
[2022-01-31 04:18:02,170] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-01-31 04:18:02,225] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=testing_dag, task_id=wget, execution_date=20220131T041759, start_date=20220131T041801, end_date=20220131T041802
[2022-01-31 04:18:02,308] {standard_task_runner.py:92} ERROR - Failed to execute job 88 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-01-31 04:18:02,368] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-31 04:18:02,525] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
