[2022-02-01 22:51:07,036] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testing_dag.wget scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-02-01 22:51:07,097] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testing_dag.wget scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2022-02-01 22:51:07,103] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 22:51:07,106] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-01 22:51:07,109] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 22:51:07,188] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2019-05-02 06:00:00+00:00
[2022-02-01 22:51:07,198] {standard_task_runner.py:52} INFO - Started process 5112 to run task
[2022-02-01 22:51:07,217] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'wget', 'scheduled__2019-05-02T06:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/testing_dag.py', '--cfg-path', '/tmp/tmpml4q3vxb', '--error-file', '/tmp/tmpvnazh81h']
[2022-02-01 22:51:07,222] {standard_task_runner.py:77} INFO - Job 193: Subtask wget
[2022-02-01 22:51:07,490] {logging_mixin.py:109} INFO - Running <TaskInstance: testing_dag.wget scheduled__2019-05-02T06:00:00+00:00 [running]> on host e865aa3c139a
[2022-02-01 22:51:07,864] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-01 22:51:07,930] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=testing_dag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2019-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-05-02T06:00:00+00:00
[2022-02-01 22:51:07,942] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-01 22:51:07,950] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-05.csv > /opt/***/output_2019-05.csv']
[2022-02-01 22:51:07,983] {subprocess.py:85} INFO - Output:
[2022-02-01 22:55:01,066] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-02-01 22:55:01,201] {subprocess.py:93} INFO - Command exited with return code 56
[2022-02-01 22:55:01,531] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-02-01 22:55:01,787] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=testing_dag, task_id=wget, execution_date=20190502T060000, start_date=20220201T225107, end_date=20220201T225501
[2022-02-01 22:55:02,246] {standard_task_runner.py:92} ERROR - Failed to execute job 193 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-02-01 22:55:02,390] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-01 22:55:02,824] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
