[2022-02-02 21:45:59,232] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_ingest_2_gcs_dag.upload_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-02 21:45:59,298] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_ingest_2_gcs_dag.upload_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-02 21:45:59,301] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 21:45:59,302] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 21:45:59,304] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 21:45:59,415] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): upload_to_gcs_job> on 2019-03-02 06:00:00+00:00
[2022-02-02 21:45:59,435] {standard_task_runner.py:52} INFO - Started process 1403 to run task
[2022-02-02 21:45:59,469] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_ingest_2_gcs_dag', 'upload_to_gcs_job', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/fhv_download_ingest_gcs.py', '--cfg-path', '/tmp/tmp1d3kz23c', '--error-file', '/tmp/tmpg1uvk9m1']
[2022-02-02 21:45:59,476] {standard_task_runner.py:77} INFO - Job 437: Subtask upload_to_gcs_job
[2022-02-02 21:45:59,993] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_ingest_2_gcs_dag.upload_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [running]> on host ee5c3eebd1b1
[2022-02-02 21:46:00,247] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 21:46:00,347] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_ingest_2_gcs_dag
AIRFLOW_CTX_TASK_ID=upload_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-02-02 21:46:00,543] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fhv_download_ingest_gcs.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-03.parquet'
[2022-02-02 21:46:00,633] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=fhv_ingest_2_gcs_dag, task_id=upload_to_gcs_job, execution_date=20190302T060000, start_date=20220202T214559, end_date=20220202T214600
[2022-02-02 21:46:00,700] {standard_task_runner.py:92} ERROR - Failed to execute job 437 for task upload_to_gcs_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fhv_download_ingest_gcs.py", line 52, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-03.parquet'
[2022-02-02 21:46:00,783] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-02 21:46:01,026] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-02 21:52:37,247] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_ingest_2_gcs_dag.upload_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-02 21:52:37,373] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_ingest_2_gcs_dag.upload_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-02-02 21:52:37,379] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 21:52:37,380] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 21:52:37,394] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 21:52:37,492] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): upload_to_gcs_job> on 2019-03-02 06:00:00+00:00
[2022-02-02 21:52:37,527] {standard_task_runner.py:52} INFO - Started process 1853 to run task
[2022-02-02 21:52:37,564] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_ingest_2_gcs_dag', 'upload_to_gcs_job', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '448', '--raw', '--subdir', 'DAGS_FOLDER/fhv_download_ingest_gcs.py', '--cfg-path', '/tmp/tmpsxq79zax', '--error-file', '/tmp/tmpbpiu6r9f']
[2022-02-02 21:52:37,587] {standard_task_runner.py:77} INFO - Job 448: Subtask upload_to_gcs_job
[2022-02-02 21:52:37,854] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_ingest_2_gcs_dag.upload_to_gcs_job scheduled__2019-03-02T06:00:00+00:00 [running]> on host ee5c3eebd1b1
[2022-02-02 21:52:38,175] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 21:52:38,286] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_ingest_2_gcs_dag
AIRFLOW_CTX_TASK_ID=upload_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-02-02 21:52:41,751] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 21:52:41,829] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_ingest_2_gcs_dag, task_id=upload_to_gcs_job, execution_date=20190302T060000, start_date=20220202T215237, end_date=20220202T215241
[2022-02-02 21:52:41,954] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 21:52:42,100] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
