[2022-01-31 04:28:57,980] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testing_dag.wget manual__2022-01-31T04:22:11.252850+00:00 [queued]>
[2022-01-31 04:28:58,019] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testing_dag.wget manual__2022-01-31T04:22:11.252850+00:00 [queued]>
[2022-01-31 04:28:58,021] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 04:28:58,023] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-31 04:28:58,024] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 04:28:58,068] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-01-31 04:22:11.252850+00:00
[2022-01-31 04:28:58,076] {standard_task_runner.py:52} INFO - Started process 5624 to run task
[2022-01-31 04:28:58,085] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'testing_dag', 'wget', 'manual__2022-01-31T04:22:11.252850+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/testing_dag.py', '--cfg-path', '/tmp/tmpl8spqhlf', '--error-file', '/tmp/tmpfinu8blm']
[2022-01-31 04:28:58,088] {standard_task_runner.py:77} INFO - Job 91: Subtask wget
[2022-01-31 04:28:58,243] {logging_mixin.py:109} INFO - Running <TaskInstance: testing_dag.wget manual__2022-01-31T04:22:11.252850+00:00 [running]> on host 5beebf73c64a
[2022-01-31 04:28:58,403] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=testing_dag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T04:22:11.252850+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-31T04:22:11.252850+00:00
[2022-01-31 04:28:58,409] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-31 04:28:58,412] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv -O /opt/***/output.csv']
[2022-01-31 04:28:58,434] {subprocess.py:85} INFO - Output:
[2022-01-31 04:28:58,480] {subprocess.py:89} INFO - /bin/bash: wget: command not found
[2022-01-31 04:28:58,483] {subprocess.py:93} INFO - Command exited with return code 127
[2022-01-31 04:28:58,525] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-01-31 04:28:58,555] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=testing_dag, task_id=wget, execution_date=20220131T042211, start_date=20220131T042857, end_date=20220131T042858
[2022-01-31 04:28:58,599] {standard_task_runner.py:92} ERROR - Failed to execute job 91 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-01-31 04:28:58,633] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-31 04:28:58,744] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
